### ISSUE TITLE
能提供一个模型测试用吗

### ISSUE THREAD

**Issue by WenmuZhou** [saicoco/SA-Text#2]

**Comment by fxwfzsxyq** [comment]
mark

**Comment by saicoco** [comment]
@WenmuZhou 抱歉，回复晚了，刚整理了模型，已经放了[release](https://github.com/saicoco/SA-Text/releases/tag/v0.1)。关于模型的效果，主要在于gaussian map的准确性和后处理：gaussian map的gaussian kernel设置不合理容易导致密集文本的粘连，当然通过卡阈值可以避免；后处理为了快速，直接获取连通域+膨胀得到文本实例，更优雅的做法可以借鉴PSENet的后处理，逐步合并像素得到实例。最终的效果没有文中所说的那么好，不过验证了gaussian map在一些场景比binary map有优势，泛化性更好。

gaussian map的接近0的部分属于3sigma区域，但是这部分也是引起粘连的部分，想改进它从这里是一个很好的入手点。就说这么多吧，欢迎交流

**Comment by WenmuZhou** [comment]
好的，谢谢回复，之前一直没做过高斯map相关的工作，我先研究下这篇文章

**Comment by saicoco** [comment]
关于gaussian map部分可以参考simple pose或者MSRA-gaussian的生成方法以及相关理论，同时centernet的issue区也有相关的讨论，可以参考

**Comment by WenmuZhou** [comment]
我自己写了一版，icdar2015只能搞到66

**Comment by saicoco** [comment]
这个模型很容易预测成行，而且边界不稳定，泛化性可以，准确性差点，不知道paper里面是不是有别的trick

**Comment by menglingrui** [comment]
> 我自己写了一版，icdar2015只能搞到66

我搞到了75，就是文本黏连问题比较严重

**Comment by zcswdt** [comment]
> > 我自己写了一版，icdar2015只能搞到66
> 
> 我搞到了75，就是文本黏连问题比较严重

请问一下，您这个75是如何做的呢？可以请教一下吗？
